---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 1-core-db-pg-clusters-home
  namespace: flux-system
  annotations:
    description: "This Postgres cluster is for 'sensitive'-enough data related to home use, that shouldn't be accessible from other apps."
  labels:
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  path: ./kube/deploy/core/db/pg/clusters/template
  dependsOn:
    - name: 1-core-db-pg-app
    - name: 1-core-storage-democratic-csi-local-hostpath
    - name: 1-core-secrets-es-k8s
  postBuild:
    substitute:
      PG_APP_NAME: &app "home"
      PG_APP_NS: "pg"
      PG_DB_NAME: "postgres"
      PG_DB_USER: "postgres"
      PG_REPLICAS: "3"
      PG_SC: "local-xfs"
      PG_CONFIG_VERSION: "16"
      PG_CONFIG_SIZE: "10Gi"
      PG_DUMPALL: !!str "'TRUE'"
      PG_DUMP_FROM: "primary"
  patches:
    - target:
        group: postgres-operator.crunchydata.com
        kind: PostgresCluster
      patch: |-
        apiVersion: postgres-operator.crunchydata.com/v1beta1
        kind: PostgresCluster
        metadata:
          name: not-used
        spec:
          users:
            - name: "postgres"
            - name: "firefly"
              databases: ["firefly"]
            - name: "paperless-ngx"
              databases: ["paperless-ngx"]
            - name: "joplin"
              databases: ["joplin"]
            - name: "vikunja"
              databases: ["vikunja"]
            - name: "kanboard"
              databases: ["kanboard"]
            - name: "reactive-resume"
              databases: ["reactive-resume"]
            - name: "linkding"
              databases: ["linkding"]
            - name: "davis"
              databases: ["davis"]
              password:
                type: "AlphaNumeric" # Otherwise, PHP Symfony will throw "this parameter must be defined" errors, e.g. `This parameter "3C+" must be defined`, where 3C+ is a part of the password
            - name: "immich"
              databases: ["immich"]
            - name: "gotosocial"
              databases: ["gotosocial"]
          patroni:
            dynamicConfiguration:
              synchronous_mode: true
              postgresql:
                synchronous_commit: "on"
                pg_hba:
                  - hostnossl reactive-resume reactive-resume all md5
                  - hostssl all all all md5
    - target:
        group: postgresql.cnpg.io
        kind: Cluster
      patch: |-
        - op: add
          path: /spec/postgresql/shared_preload_libraries/-
          value: vchord.so
        - op: add
          path: /spec/postgresql/extensions
          value:
            - name: vchord
              image:
                reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1
              dynamic_library_path:
                - /usr/lib/postgresql/18/lib
              extension_control_path:
                - /usr/share/postgresql/18/
  healthChecks:
    - apiVersion: postgres-operator.crunchydata.com/v1beta1
      kind: PostgresCluster
      name: pg-home
      namespace: pg
