---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
  namespace: *app
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: *app
  values:
    controllers:
      app:
        type: deployment
        replicas: 1
        pod:
          labels:
            ingress.home.arpa/world: allow
            egress.home.arpa/internet: allow
        containers:
          app:
            image: &img
              repository: ghcr.io/itzg/minecraft-server
              tag: 2026.7.0@sha256:5ffbc91d933e2f0e194a4f49674a2d17b65bb051c86e61961a6c775312ef61c0
            env:
              TZ: "${CONFIG_TZ}"
              MEMORY: "2048M"
              EULA: "TRUE"
              TYPE: "VANILLA"
              VERSION: "26.2"
              OVERRIDE_ICON: "TRUE"
              MOTD: "Never waste your diamonds on a hoe!"
              LEVEL_TYPE: "DEFAULT"
              LEVEL: "world"
              MODE: "survival"
              DIFFICULTY: "normal"
              MAX_WORLD_SIZE: "6e+07"
              MAX_PLAYERS: "20"
              PVP: "true"
              ALLOW_NETHER: "true"
              ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
              ENABLE_COMMAND_BLOCK: "false"
              FORCE_GAMEMODE: "true"
              GENERATE_STRUCTURES: "true"
              HARDCORE: "false"
              MAX_BUILD_HEIGHT: "256"
              MAX_TICK_TIME: "-1"
              VIEW_DISTANCE: "10"
              OVERRIDE_SERVER_PROPERTIES: "true"
              ENABLE_RCON: "true"
              ENABLE_AUTOPAUSE: "TRUE"
              SKIP_SUDO: "true"
              AUTOPAUSE_SUDO: "false"
              AUTOPAUSE_KNOCK_INTERFACE: "eth0"
              AUTOPAUSE_TIMEOUT_EST: "300"
              AUTOPAUSE_TIMEOUT_INIT: "120"
              RCON_CMDS_STARTUP: |-
                gamerule keepInventory false
              SNOOPER_ENABLED: "false"
              SYNC_CHUNK_WRITES: "false"
              USE_AIKAR_FLAGS: "true"
            envFrom: &envFrom
              - secretRef:
                  name: minecraft-secrets
            securityContext: &sc
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: true
              capabilities:
                drop: ["ALL"]
                add: ["NET_RAW"]
            resources:
              requests:
                cpu: "10m"
              limits:
                # cpu: "4"
                memory: "4Gi"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  periodSeconds: 60
                  exec: &probeexec {command: ["mc-health"]}
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  initialDelaySeconds: 30
                  periodSeconds: 1
                  failureThreshold: 300
                  exec: *probeexec
    service:
      app:
        controller: app
        type: LoadBalancer
        annotations:
          coredns.io/hostname: "${APP_DNS_MINECRAFT:=minecraft}"
          lbipam.cilium.io/ips: "${APP_IP_MINECRAFT:=127.0.0.1}"
        ports:
          http:
            port: 25565
            protocol: TCP
    persistence:
      data:
        existingClaim: minecraft-data
        advancedMounts:
          app:
            app:
              - subPath: data
                path: /data
      tmp:
        type: emptyDir
        medium: Memory
        globalMounts:
          - subPath: tmp
            path: /tmp
    defaultPodOptions:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      # hostUsers: false
      runtimeClassName: gvisor
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 1000
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: "Unconfined" }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "fuckoff.home.arpa/{{ .Release.Name }}"
                    operator: DoesNotExist
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 15
              preference:
                matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: "In"
                    values: [dorothy] # MS01 worker
            - weight: 10
              preference:
                matchExpressions:
                  - key: "kubernetes.io/hostname"
                    operator: "In"
                    values: [ange, charlotte, chise] # HP 400 G9 controlplane
