---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "llama-cpp-misc"
  namespace: &app "llama-cpp"
  annotations:
    description: "PVC for misc files that don't need to be backed up, like models."
  labels:
    app.kubernetes.io/name: *app
    kustomize.toolkit.fluxcd.io/prune: "Disabled"
spec:
  storageClassName: "file-size-2"
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: "150Gi"
