---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-5.0.1/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app satisfactory
  namespace: *app
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: *app
  values:
    controllers:
      app:
        type: deployment
        replicas: 1
        pod:
          labels:
            ingress.home.arpa/lan: allow
            ingress.home.arpa/jjgadgets: allow
            ingress.home.arpa/wg-guest: allow
            egress.home.arpa/internet: allow
        containers:
          app:
            image: &img
              repository: docker.io/wolveix/satisfactory-server
              tag: v1.9.10@sha256:e103700ae6ae4c50f19dac80eadb2a805c5b885e179ae2a40850e967bf189efd
            securityContext: &sc
              runAsUser: ${APP_UID_SATISFACTORY:=1000}
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            env:
              TZ: "${CONFIG_TZ}"
              ROOTLESS: "true"
              AUTOPAUSE: "true"
              AUTOSAVEINTERVAL: "60"
              AUTOSAVENUM: "60"
              AUTOSAVEONDISCONNECT: "true"
              CRASHREPORT: "false"
              MAXPLAYERS: "4"
              MAXTICKRATE: "120" # default is a low 30
              NETWORKQUALITY: "3" # 0-3, 3 is Ultra (default)
              TIMEOUT: "300"
            resources:
              requests:
                cpu: "200m"
              limits:
                cpu: "3000m"
                memory: "20Gi"
        initContainers:
          01-cp:
            image: *img
            command: ["/bin/sh", "-c", "cp -r /home/steam/. /home/fake/"]
            securityContext: *sc
            resources: {}
    service:
      app:
        controller: app
        ports:
          game:
            port: 7777
            targetPort: 7777
            protocol: UDP
          beacon:
            port: 15000
            targetPort: 15000
            protocol: UDP
          query:
            port: 15777
            targetPort: 15777
            protocol: UDP
      expose:
        primary: false
        controller: app
        type: LoadBalancer
        annotations:
          coredns.io/hostname: "${APP_DNS_SATISFACTORY:=satisfactory}"
          "io.cilium/lb-ipam-ips": "${APP_IP_SATISFACTORY:=127.0.0.1}"
        ports:
          game:
            port: 7777
            targetPort: 7777
            protocol: UDP
          beacon:
            port: 15000
            targetPort: 15000
            protocol: UDP
          query:
            port: 15777
            targetPort: 15777
            protocol: UDP
    persistence:
      data:
        existingClaim: satisfactory-data
        advancedMounts:
          app:
            app:
              - path: /config
      game:
        existingClaim: satisfactory-game
        advancedMounts:
          app:
            app:
              - subPath: game
                path: /config/gamefiles
      tmp:
        type: emptyDir
        medium: Memory
        advancedMounts:
          app:
            01-cp:
              - subPath: configdir
                path: /home/fake
            app:
              - subPath: configdir
                path: /home/steam
              - subPath: tmp
                path: /tmp
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      securityContext:
        runAsNonRoot: true
        runAsUser: ${APP_UID_SATISFACTORY:=1000}
        runAsGroup: ${APP_UID_SATISFACTORY:=1000}
        fsGroup: ${APP_UID_SATISFACTORY:=1000}
        fsGroupChangePolicy: Always
        seccompProfile: { type: "RuntimeDefault" }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "fuckoff.home.arpa/{{ .Release.Name }}"
                    operator: DoesNotExist
