---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mollysocket-app
  namespace: &ns mollysocket
  labels: &l
    app.kubernetes.io/name: "mollysocket"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/mollysocket/app
  components:
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: mollysocket-pvc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mollysocket-pvc
  namespace: &ns mollysocket
  labels: &l
    app.kubernetes.io/name: mollysocket
    pvc.home.arpa/volsync: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: &pvc "mollysocket-data"
      SIZE: "1Gi"
      SC: &sc "file"
      SNAP: *sc
      ACCESSMODE: "ReadWriteMany"
      SNAP_ACCESSMODE: "ReadOnlyMany"
      VS_APP_CURRENT_VERSION: "ghcr.io/mollyim/mollysocket:1.7.1-alpine@sha256:faaaa4634a9d049fa2fd17fa0c37228c460a841bc6015ab55bf498cd95fe84ba"
      RUID: &uid "1000"
      RGID: *uid
      RFSG: *uid
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "mollysocket-data-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed"
