---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name k8s-schemas-secrets
  namespace: k8s-schemas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: "k8s-schemas - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
