---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: esphome-app
  namespace: &ns esphome
  labels: &l
    app.kubernetes.io/name: "esphome"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/esphome/app
  components:
    - "../../../../repos/flux/helm-oci/app-template/"
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: esphome-pvc
  postBuild:
    substitute:
      APP_TEMPLATE: "5.0.1"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: esphome-pvc
  namespace: &ns esphome
  labels: &l
    app.kubernetes.io/name: esphome
    pvc.home.arpa/volsync: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: &pvc "esphome-data"
      SIZE: "10Gi"
      SC: &sc "file"
      SNAP: *sc
      ACCESSMODE: "ReadWriteMany"
      SNAP_ACCESSMODE: "ReadOnlyMany"
      VS_APP_CURRENT_VERSION: "ghcr.io/home-operations/esphome:2026.7.3@sha256:243405d1349d6ad7b656753235a5ca96df603886f3bd970f6012d4d6ae9ce27d"
      RUID: &uid "1000"
      RGID: *uid
      RFSG: *uid
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "esphome-data-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed"
