---
# yaml-language-server: $schema=https://flux.jank.ing/ocirepository-source-v1.json?test
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: app-template
  namespace: memini
spec:
  url: oci://registry.erwanleboucher.dev/eleboucher/charts/memini
  ref:
    tag: v0.7.25
