---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: "${PG_DB_USER}"
spec:
  name: "${PG_DB_USER}"
  owner: "${PG_DB_USER}"
  cluster:
    name: "pg-${PG_NAME}"
  ensure: present
  databaseReclaimPolicy: retain
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: "${PG_DB_USER}"
spec:
  cluster:
    name: "pg-${PG_NAME}"
  name: "${PG_DB_USER}"
  ensure: present
  login: true
  superuser: false
  createdb: false # perms of the user, not whether to create a DB
  createrole: false # perms of the user, not whether to create this role
  inherit: true
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: "pg-${PG_NAME}-pguser-${PG_DB_USER}-cnpg"
  clientCertificate:
    enabled: true
