---
# NOTE: below is CNPG
---
# yaml-language-server: $schema=https://crds.jank.ing/generators.external-secrets.io/password_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: "pg-${PG_NAME}-pguser-${PG_DB_USER}-cnpg"
  # namespace: "${PG_NS}"
spec:
  secretKeys: ["password"]
  length: 90
  symbolCharacters: "~!$+-|:<>," # https://dba.stackexchange.com/a/286348
  noUpper: false
  allowRepeat: true
---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "pg-${PG_NAME}-pguser-${PG_DB_USER}-cnpg"
  # namespace: "${PG_NS}"
spec:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: *name
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        # host: "pg-${PG_NAME}-rw.${PG_NS}.svc.cluster.local."
        # jdbc-uri: "jdbc:postgresql://pg-${PG_NAME}-rw.${PG_NS}.svc.cluster.local.:5432/${PG_DB_USER}?password={{ .password }}&user=${PG_DB_USER}"
        # uri: "postgresql://${PG_DB_USER}:{{ .password }}@pg-${PG_NAME}-rw.${PG_NS}.svc.cluster.local.:5432/${PG_DB_USER}"
        username: "${PG_DB_USER}"
        password: '{{ .password }}'
