---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: &app cnpg
  namespace: *app
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    tag: 0.28.0
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/cloudnative-pg/charts.*$"
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cnpg
  namespace: *app
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
    namespace: *app
  values:
    crds:
      create: true
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: plugin-barman-cloud
  namespace: &ns cnpg
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/cloudnative-pg/charts/plugin-barman-cloud
  ref:
    tag: 0.6.0
  verify:
    provider: cosign
    matchOIDCIdentity:
      - issuer: "^https://token.actions.githubusercontent.com$"
        subject: "^https://github.com/cloudnative-pg/charts.*$"
---
# yaml-language-server: $schema=https://k8s-schemas.m00nlit.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app plugin-barman-cloud
  namespace: &ns cnpg
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: *app
    namespace: *ns
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app crunchy-pgo
  namespace: *app
spec:
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  chart:
    spec:
      chart: pgo
      version: 5.5.1
      sourceRef:
        name: crunchydata
        kind: HelmRepository
        namespace: flux-system
