---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fortidynasync-app
  namespace: &ns fortidynasync
  labels: &l
    app.kubernetes.io/name: "fortidynasync"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/fortidynasync/app
  dependsOn: []
  components:
    - ../../../core/flux-system/alerts/template/
