---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cyberchef-app
  namespace: &ns cyberchef
  labels: &l
    app.kubernetes.io/name: "cyberchef"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/cyberchef/app
  components:
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
