---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: "${PVC:0:50}-v${VS_APP_CURRENT_VERSION#*@sha256:?????????????????????????????????????????????????????}"
spec:
  volumeSnapshotClassName: "${SNAP:=file}"
  source:
    persistentVolumeClaimName: "${PVC}"
