---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name mindwtr-secrets
  namespace: mindwtr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: "mindwtr - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        MINDWTR_CLOUD_AUTH_TOKENS: '{{ .password }}'
        MINDWTR_CLOUD_CORS_ORIGIN: 'https://{{ .APP_DNS_MINDWTR }}'
