---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: talosctl-image-pull-agent-app
  namespace: &ns talosctl-image-pull-agent
  labels: &l
    app.kubernetes.io/name: "talosctl-image-pull-agent"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/talosctl-image-pull-agent/app
  components:
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
