---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${CLUSTER_NAME:=biohazard}-vars"
  namespace: rclone-retro
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: ".${CLUSTER_NAME}-vars"
    - extract:
        key: "rclone-retro - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        # Core cluster-wide vars
        CLUSTER_NAME: "${CLUSTER_NAME:=biohazard}"
        CONFIG_TZ: '{{ .CONFIG_TZ }}'
        # App specific
        APP_DNS_RCLONE_RETRO: '{{ .APP_DNS_RCLONE_RETRO }}'
        APP_DNS_RCLONE_RETRO_FTP: '{{ .APP_DNS_RCLONE_RETRO_FTP }}'
        APP_IP_RCLONE_RETRO_FTP: '{{ .APP_IP_RCLONE_RETRO_FTP }}'
        # Authentik hostAliases
        APP_DNS_AUTHENTIK: '{{ .APP_DNS_AUTHENTIK }}'
        APP_IP_AUTHENTIK: '{{ .APP_IP_AUTHENTIK }}'
        # Other cluster-wide vars
        IP_JJ_V4: '{{ .IP_JJ_V4 }}'
        IP_VLAN_RETROCONSOLES_CIDR: '{{ .IP_VLAN_RETROCONSOLES_CIDR }}'
        IP_VLAN_NDS_CIDR: '{{ .IP_VLAN_NDS_CIDR }}'
