---
# yaml-language-server: $schema=https://flux.jank.ing/ocirepository-source-v1.json?test
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: app-template
  namespace: bluesky
spec:
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    tag: 4.6.2@sha256:1bf84c8236b2346c49a21de13180e3e46eb5be34edf79f50e90bc1923721af0e
