---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app audiobookshelf
  namespace: *app
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: *app
  values:
    controllers:
      app:
        type: deployment
        replicas: 1
        pod:
          labels:
            ingress.home.arpa/envoy-internal: allow
            egress.home.arpa/world: allow
        containers:
          app:
            image: &img
              repository: ghcr.io/advplyr/audiobookshelf
              tag: "2.36.0@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e"
            env:
              TZ: "${CONFIG_TZ}"
              PORT: &http "8080"
              CONFIG_PATH: &config "/config"
              METADATA_PATH: &meta "/metadata"
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: "10m"
                memory: "128Mi"
              limits:
                memory: "6000Mi"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
    service:
      app:
        controller: app
        ports:
          http:
            port: 80
            targetPort: *http
            protocol: HTTP
            appProtocol: http
    route:
      app:
        hostnames: ["${APP_DNS_AUDIOBOOKSHELF:=audiobookshelf}"]
        parentRefs:
          - name: envoy-internal
            namespace: ingress
            sectionName: internal
    persistence:
      config:
        existingClaim: audiobookshelf-config
        advancedMounts:
          app:
            app:
              - path: *config
      nfs:
        enabled: true
        type: nfs
        server: "${IP_TRUENAS:=127.0.0.1}"
        path: "${PATH_NAS_MEDIA:=/media}"
        advancedMounts:
          app:
            app:
              - subPath: ".audiobookshelf-metadata"
                path: *meta
              - subPath: "Podcasts"
                path: "/podcasts"
              - subPath: "Audiobooks"
                path: "/audiobooks"
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      runtimeClassName: gvisor
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid ${APP_UID_AUDIOBOOKSHELF:=1000}
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: Always
        seccompProfile: { type: "RuntimeDefault" }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "fuckoff.home.arpa/{{ .Release.Name }}"
                    operator: DoesNotExist
