---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${CLUSTER_NAME:=biohazard}-vars"
  namespace: velociraptor
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: ".${CLUSTER_NAME}-vars"
    - extract:
        key: "velociraptor - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        # Core cluster-wide vars
        CLUSTER_NAME: "${CLUSTER_NAME:=biohazard}"
        CONFIG_TZ: '{{ .CONFIG_TZ }}'
        # App specific
        APP_DNS_VELOCIRAPTOR: '{{ .APP_DNS_VELOCIRAPTOR }}'
        APP_UID_VELOCIRAPTOR: '{{ .APP_UID_VELOCIRAPTOR }}'
        # Other cluster-wide vars
        APP_DNS_AUTH: '{{ .APP_DNS_AUTH }}'
        IP_OLD_DOCKER: '{{ .IP_OLD_DOCKER }}'
        IP_EC2_INGRESS: '{{ .IP_EC2_INGRESS }}'
