---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: go2rtc-app
  namespace: &ns go2rtc
  labels: &l
    app.kubernetes.io/name: "go2rtc"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/go2rtc/app
  components:
    - ../../../core/flux-system/alerts/template/
    - ../../../../repos/flux/helm-oci/app-template/
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      APP_TEMPLATE: "5.0.1"
