---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openclaw-app
  namespace: &ns openclaw
  labels: &l
    app.kubernetes.io/name: "openclaw"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/openclaw/app
  components:
    - ../../../core/flux-system/alerts/template/
    - ../../../core/ingress/envoy-gateway/forward-auth/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: openclaw-pvc
  postBuild:
    substitute:
      AUTH_ROUTE: openclaw
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openclaw-pvc
  namespace: &ns openclaw
  labels: &l
    app.kubernetes.io/name: openclaw
    pvc.home.arpa/volsync: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: &pvc "openclaw-data"
      SIZE: "10Gi"
      SC: &sc "block"
      SNAP: *sc
      ACCESSMODE: &am "ReadWriteOnce"
      SNAP_ACCESSMODE: *am
      VS_APP_CURRENT_VERSION: "ghcr.io/openclaw/openclaw:2026.6.1@sha256:b12f76a7947e4cdd328bf3ea1045d41a5494b33852c911e9bc4fdd03dde469d5"
      RUID: &uid "1000" # upstream `node` user
      RGID: *uid
      RFSG: *uid
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "openclaw-data-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed"
