---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${CLUSTER_NAME:=biohazard}-vars"
  namespace: openclaw
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: ".${CLUSTER_NAME}-vars"
    - extract:
        key: "authentik vars - ${CLUSTER_NAME}"
    - extract:
        key: "OpenClaw - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        # Core cluster-wide vars
        CLUSTER_NAME: "${CLUSTER_NAME:=biohazard}"
        CONFIG_TZ: '{{ .CONFIG_TZ }}'
        # App specific
        APP_DNS_OPENCLAW: '{{ .APP_DNS_OPENCLAW }}'
        # APP_UID_OPENCLAW: '{{ .APP_UID_OPENCLAW }}'
        # APP_IP_OPENCLAW: '{{ .APP_IP_OPENCLAW }}'
        APP_IP_OPENCLAW_VPN: '{{ .APP_IP_OPENCLAW_VPN }}'
        # APP_IP_OPENCLAW_VPN: '{{ .APP_IP_OPENCLAW_VPN }}'
        # Other cluster-wide vars
        IP_JJ_V4: '{{ .IP_JJ_V4 }}'
        IP_TRUENAS: '{{ .IP_TRUENAS }}'
        PATH_NAS_PERSIST_K8S: '{{ .PATH_NAS_PERSIST_K8S }}'
