---
# yaml-language-server: $schema=https://crds.jank.ing/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name continuwuity-secrets
  namespace: continuwuity
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: "Continuwuity - ${CLUSTER_NAME}"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        CONDUWUIT_REGISTRATION_TOKEN: '{{ .CONDUWUIT_REGISTRATION_TOKEN }}'
        CONDUWUIT_EMERGENCY_PASSWORD: '{{ .CONDUWUIT_EMERGENCY_PASSWORD }}'
        CONDUWUIT_OAUTH__OIDC__DISCOVERY_URL: '{{ .CONDUWUIT_OAUTH__OIDC__DISCOVERY_URL }}'
        CONDUWUIT_OAUTH__OIDC__CLIENT_ID: '{{ .CONDUWUIT_OAUTH__OIDC__CLIENT_ID }}'
        CONDUWUIT_OAUTH__OIDC__CLIENT_SECRET: '{{ .CONDUWUIT_OAUTH__OIDC__CLIENT_SECRET }}'
