---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ntfy
  namespace: *app
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: *app
  values:
    controllers:
      app:
        type: deployment
        replicas: 1
        pod:
          labels:
            ingress.home.arpa/envoy-internal: allow
        containers:
          app:
            image: &img
              repository: p.jank.me/binwiederhier/ntfy
              tag: v2.18.0@sha256:bf4b67bea925d80e8400ae2997111c933772c8c5f16d7b49f33aa2d27d837098
            command: ["ntfy", "serve"]
            env: &env
              TZ: "${CONFIG_TZ}"
              NTFY_BASE_URL: "https://${APP_DNS_NTFY}"
              AAA_HTTP: &http 8080
              NTFY_LISTEN_HTTP: ":$(AAA_HTTP)"
              NTFY_BEHIND_PROXY: "true"
              NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh" # for iOS
              NTFY_CACHE_DURATION: "24h"
              NTFY_CACHE_FILE: "/data/cache.db"
              NTFY_AUTH_FILE: "/data/authfile.db"
              # NTFY_WEB_PUSH_FILE: "/data/webpush.db"
              NTFY_ATTACHMENT_CACHE_DIR: "/data/attachments"
              NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
              AAA_SMTP: &smtp 2525
              NTFY_SMTP_SERVER_LISTEN: ":$(AAA_SMTP)"
              NTFY_SMTP_SERVER_DOMAIN: "${APP_DNS_NTFY_MX}"
              NTFY_SMTP_SERVER_ADDR_PREFIX: "pushme-"
            securityContext: &sc
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: "10m"
              limits:
                cpu: "2"
                memory: "150Mi"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
        initContainers:
          02-init-unifiedpush:
            image: *img
            command: ["/bin/sh", "-c", "find /data/authfile.db && ntfy access '*' 'up*' write-only || true"]
            env: *env
            securityContext: *sc
    service:
      app:
        controller: app
        ports:
          http:
            port: 80
            targetPort: *http
            protocol: HTTP
            appProtocol: http
      expose:
        primary: false
        controller: app
        type: LoadBalancer
        annotations:
          coredns.io/hostname: "${APP_DNS_NTFY_MX:=ntfy}"
          lbipam.cilium.io/ips: "${APP_IP_NTFY_MX:=127.0.0.1}"
        ports:
          smtp-tcp: &smtp-svc
            port: 25
            targetPort: *smtp
            protocol: TCP
            appProtocol: smtp
          smtp-udp:
            <<: *smtp-svc
            protocol: UDP
    route:
      app:
        # annotations:
        #   external-dns.alpha.kubernetes.io/target: "${DNS_CF:=cf}"
        #   external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hostnames: ["${APP_DNS_NTFY:=ntfy}"]
        parentRefs:
          - name: envoy-internal
            namespace: ingress
            sectionName: internal
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      data:
        existingClaim: ntfy-data
        advancedMounts:
          app:
            app:
              - subPath: data
                path: /data
      # tls:
      #   type: secret
      #   name: short-domain-tls
      #   defaultMode: 0400
      #   advancedMounts:
      #     app:
      #       app:
      #         - subPath: tls.crt
      #           path: /tls/fullchain.pem
      #           readOnly: true
      #         - subPath: tls.key
      #           path: /tls/privkey.pem
      #           readOnly: true
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      runtimeClassName: kata
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 65534
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: Always
        seccompProfile: { type: "RuntimeDefault" }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "fuckoff.home.arpa/{{ .Release.Name }}"
                    operator: DoesNotExist
