---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.6.2/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ntfy
  namespace: *app
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: *app
  values:
    controllers:
      app:
        type: deployment
        replicas: 1
        pod:
          labels:
            ingress.home.arpa/envoy-internal: allow
        containers:
          app:
            image: &img
              repository: p.jank.me/binwiederhier/ntfy
              tag: v2.23.0@sha256:b32b4221a64ec2e7c000f0782b2feef24022e1a09a24e531640f4cbba6cfa1e6
            command: ["ntfy", "serve"]
            env: &env
              TZ: "${CONFIG_TZ}"
              NTFY_BASE_URL: "https://${APP_DNS_NTFY}"
              AAA_HTTP: &http 8080
              NTFY_LISTEN_HTTP: ":$(AAA_HTTP)"
              NTFY_BEHIND_PROXY: "true"
              NTFY_PROXY_TRUSTED_HOSTS: "${IP_POD_CIDR_V4:=127.0.0.1/32}"
              AAA_HTTPS: &https 8443
              NTFY_LISTEN_HTTPS: ":$(AAA_HTTPS)"
              AAA_TLS_PATH: &tls "/tls"
              NTFY_CERT_FILE: "$(AAA_TLS_PATH)/tls.crt"
              NTFY_KEY_FILE: "$(AAA_TLS_PATH)/tls.key"
              # NTFY_UPSTREAM_BASE_URL: "https://ntfy.sh" # for iOS
              NTFY_CACHE_DURATION: "24h"
              NTFY_CACHE_FILE: "/data/cache.db"
              NTFY_AUTH_FILE: "/data/authfile.db"
              # NTFY_WEB_PUSH_FILE: "/data/webpush.db"
              NTFY_ATTACHMENT_CACHE_DIR: "/data/attachments"
              NTFY_AUTH_DEFAULT_ACCESS: "deny-all"
              AAA_SMTP: &smtp 2525
              NTFY_SMTP_SERVER_LISTEN: ":$(AAA_SMTP)"
              NTFY_SMTP_SERVER_DOMAIN: "${APP_DNS_NTFY_MX}"
              NTFY_SMTP_SERVER_ADDR_PREFIX: "pushme-"
            envFrom: &envFrom
              - secretRef:
                  name: ntfy-secrets
            securityContext: &sc
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
            resources:
              requests:
                cpu: "10m"
              limits:
                cpu: "2"
                memory: "150Mi"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
        # initContainers:
        #   02-init-unifiedpush:
        #     image: *img
        #     command: ["/bin/sh", "-c", "find /data/authfile.db && ntfy access '*' 'up*' write-only || true"]
        #     env: *env
        #     securityContext: *sc
    service:
      app:
        controller: app
        ports:
          http: &port-http
            port: 80
            targetPort: *http
            protocol: HTTP
            appProtocol: http
      expose:
        primary: false
        controller: app
        type: LoadBalancer
        annotations:
          coredns.io/hostname: "${APP_DNS_NTFY_MX:=ntfy}"
          lbipam.cilium.io/ips: "${APP_IP_NTFY_MX:=127.0.0.1}"
        ports:
          https:
            port: 443
            targetPort: *https
            protocol: HTTPS
            appProtocol: https
          smtp-tcp: &smtp-svc
            port: 25
            targetPort: *smtp
            protocol: TCP
            appProtocol: smtp
          smtp-udp:
            <<: *smtp-svc
            protocol: UDP
    route:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: "${DNS_CF:=cf}"
          external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
        hostnames: ["${APP_DNS_NTFY:=ntfy}"]
        parentRefs:
          - name: envoy-internal
            namespace: ingress
            sectionName: internal
        rules:
          - backendRefs:
              - identifier: app
                port: http
    persistence:
      data:
        existingClaim: ntfy-data
        advancedMounts:
          app:
            app: &pvc
              - subPath: data
                path: /data
            02-init-unifiedpush: *pvc
      tls:
        type: secret
        name: short-domain-tls
        defaultMode: 0400
        advancedMounts:
          app:
            app:
              - path: *tls
    defaultPodOptions:
      automountServiceAccountToken: false
      enableServiceLinks: false
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      runtimeClassName: gvisor
      securityContext:
        runAsNonRoot: true
        runAsUser: &uid 65534
        runAsGroup: *uid
        fsGroup: *uid
        fsGroupChangePolicy: Always
        seccompProfile: { type: "RuntimeDefault" }
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "fuckoff.home.arpa/{{ .Release.Name }}"
                    operator: DoesNotExist
