---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: code-server-app
  namespace: &ns code-server
  labels: &l
    app.kubernetes.io/name: "code-server"
    wait.flux.home.arpa/disabled: "true"
    wait.flux.home.arpa/enabled: "false"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/code-server/app
  components:
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: code-server-pvc
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: code-server-pvc
  namespace: &ns code-server
  labels: &l
    app.kubernetes.io/name: code-server
    pvc.home.arpa/volsync: "true"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: &pvc "code-server-data"
      SIZE: "50Gi"
      CACHESIZE: "15Gi"
      RGW_CRON: "0 */12 * * *"
      SC: &sc "block"
      SNAP: *sc
      ACCESSMODE: &am "ReadWriteOnce"
      SNAP_ACCESSMODE: *am
      VS_APP_CURRENT_VERSION: "ghcr.io/coder/code-server:4.111.0@sha256:d7a7c0188e942c53e7725dc7b7990086e1701557330f7db179fa270813544dcc"
      RUID: &uid "1000"
      RGID: *uid
      RFSG: *uid
      LMEM: "3Gi"
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "code-server-data-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed"
