---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf-app
  namespace: &ns audiobookshelf
  labels: &l
    app.kubernetes.io/name: "audiobookshelf"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/audiobookshelf/app
  components:
    - ../../../core/flux-system/alerts/template/
    - ../../../../repos/flux/helm-oci/app-template/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: audiobookshelf-pvc
  postBuild:
    substitute:
      APP_TEMPLATE: "5.0.1"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf-pvc
  namespace: &ns audiobookshelf
  labels: &l
    app.kubernetes.io/name: audiobookshelf
    pvc.home.arpa/volsync: "true"
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: &pvc "audiobookshelf-config"
      SIZE: "50Gi"
      SC: &sc "file"
      SNAP: *sc
      ACCESSMODE: "ReadWriteMany"
      SNAP_ACCESSMODE: "ReadOnlyMany"
      VS_APP_CURRENT_VERSION: "ghcr.io/advplyr/audiobookshelf:2.36.0@sha256:180acad33d69c99ed208676465d8edcb268fa46967735579a7810859885b1a8e"
      RUID: &uid "1000"
      RGID: *uid
      RFSG: *uid
      CRON: "0 22 * * *"
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "audiobookshelf-config-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.conditions.filter(s, s.status == "False").all(s, s.reason == "WaitingForManual" || s.reason == "WaitingForSchedule") && status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed"
