---
# yaml-language-server: $schema=https://flux.jank.ing/ocirepository-source-v1.json?test
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: envoy-gateway
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://mirror.gcr.io/envoyproxy/gateway-helm
  ref:
    tag: v1.6.2@sha256:1ad16ce22c3f6a9e764770ea25735c5b1cffaa3809c26c2744f5dfd54f7dfdbe
