---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: soft-serve-app
  namespace: &ns soft-serve
  labels: &l
    app.kubernetes.io/name: "soft-serve"
spec:
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/soft-serve/app
  targetNamespace: *ns
  components:
    - ../../../core/flux-system/alerts/template/
  dependsOn:
    #- name: soft-serve-db
    - name: soft-serve-pvc
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: soft-serve-pvc
  namespace: &ns soft-serve
  labels: &l
    app.kubernetes.io/name: soft-serve
    pvc.home.arpa/volsync: "true"
spec:
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  targetNamespace: *ns
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: &pvc "soft-serve-data"
      SIZE: "20Gi"
      SC: &sc "file"
      SNAP: *sc
      ACCESSMODE: "ReadWriteMany"
      SNAP_ACCESSMODE: "ReadOnlyMany"
      VS_APP_CURRENT_VERSION: "ghcr.io/charmbracelet/soft-serve:v0.11.6@sha256:7742f301ab4e5c24eccf999b10aabb97ec64e18c23f693a16599071d49ae5bf4"
      RUID: !!str &uid |
        ${APP_UID_SOFT_SERVE}
      RGID: *uid
      RFSG: *uid
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "soft-serve-data-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: soft-serve-db
  namespace: &ns soft-serve
  labels: &l
    prune.flux.home.arpa/enabled: "true"
    db.home.arpa/pg: "pg-default"
    app.kubernetes.io/name: "soft-serve"
spec:
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/db/pg/clusters/template/pguser
  targetNamespace: "pg"
  dependsOn:
    - name: 1-core-db-pg-clusters-default
    - name: 1-core-secrets-es-k8s
  postBuild:
    substitute:
      PG_NAME: "default"
      PG_DB_USER: "softserve"
      PG_APP_NS: "soft-serve"
