---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: local-xfs-hostpath
  namespace: democratic-csi
spec:
  chart:
    spec:
      chart: democratic-csi
      version: 0.15.1
      sourceRef:
        name: democratic-csi
        kind: HelmRepository
        namespace: flux-system
  values:
    csiDriver:
      name: "local-xfs-hostpath.democratic-csi.${CLUSTER_NAME}.home.arpa"
      attachRequired: false
      storageCapacity: true # With storage capacity tracking, the scheduler filters out nodes which do not have enough capacity.
      fsGroupPolicy: File # fsGroupChangePolicy

    storageClasses:
      - name: local-xfs
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: WaitForFirstConsumer
        allowVolumeExpansion: true
        storageCapacity: false # controller has no ControllerExpandVolume capabilities, hence cannot do this

    volumeSnapshotClasses:
      - name: local-xfs
        deletionPolicy: Delete
        parameters:
          cluster: "${CLUSTER_NAME}"

    controller:
      enabled: true
      strategy: node
      externalProvisioner:
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
          - --node-deployment-immediate-binding=false
          - --feature-gates=Topology=true
          - --strict-topology=true
          - --enable-capacity=true
          - --capacity-ownerref-level=1
      externalSnapshotter:
        enabled: true
        extraArgs:
          - --leader-election=false
          - --node-deployment=true
      externalResizer:
        enabled: false # node level CSI resizer
      externalAttacher:
        enabled: false

      driver:
        image: &img
          registry: ghcr.io/jjgadgets/democratic-csi
          tag: xfs@sha256:42626b21c9b909327f5a2ecfe102d55ca84e325c5687b1635e0a5ba32abb1261

    node:
      driver:
        image: *img
        extraVolumeMounts:
          - name: local-xfs-hostpath
            mountPath: /var/lib/democratic-csi-local-xfs-hostpath
            mountPropagation: Bidirectional

      extraVolumes:
        - name: local-xfs-hostpath
          hostPath:
            path: /var/lib/democratic-csi-local-xfs-hostpath
            type: DirectoryOrCreate

    driver:
      config:
        driver: local-xfs-hostpath
        instance_id: ${CLUSTER_NAME}-local-xfs-hostpath
        local-xfs-hostpath:
          shareBasePath: "/var/lib/democratic-csi-local-xfs-hostpath"
          controllerBasePath: "/var/lib/democratic-csi-local-xfs-hostpath"
          dirPermissionsMode: "0770"
          dirPermissionsUser: 0
          dirPermissionsGroup: 0
