---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: excalidraw-deps
  namespace: flux-system
spec:
  path: ./kube/deploy/apps/excalidraw/deps
  dependsOn: []
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: excalidraw-app
  namespace: flux-system
spec:
  path: ./kube/deploy/apps/excalidraw/app
  dependsOn:
    - name: excalidraw-deps
  healthChecks:
    - name: excalidraw
      namespace: excalidraw
      kind: HelmRelease
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
