---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: excalidraw-app
  namespace: &ns excalidraw
  labels: &l
    app.kubernetes.io/name: "excalidraw"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  components:
    - ../../../../repos/flux/helm-oci/app-template/
  path: ./kube/deploy/apps/excalidraw/app
  dependsOn: []
  postBuild:
    substitute:
      APP_TEMPLATE: 5.0.1
