---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name "${CLUSTER_NAME:=biohazard}-vars"
  namespace: excalidraw
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p
  dataFrom:
    - extract:
        key: ".${CLUSTER_NAME}-vars"
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: *name
    template:
      type: Opaque
      data:
        CLUSTER_NAME: "${CLUSTER_NAME:=biohazard}"
        CONFIG_TZ: '{{ .CONFIG_TZ }}'
        APP_DNS_EXCALIDRAW: '{{ .APP_DNS_EXCALIDRAW }}'
        IP_EC2_INGRESS: '{{ .IP_EC2_INGRESS }}'
