---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: navidrome-app
  namespace: &ns media
  labels: &l
    app.kubernetes.io/name: &app "navidrome"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/apps/media/navidrome/app
  components:
    - ../../../../core/flux-system/alerts/template/
    - ../../../../../repos/flux/helm-oci/app-template/
    - ../../../../core/ingress/envoy-gateway/forward-auth/
  dependsOn:
    - name: crds
      namespace: flux-system
    - name: navidrome-pvc
  postBuild:
    substitute:
      APP_TEMPLATE: 4.6.2
      CHART_NAME: *app
      AUTH_ROUTE: navidrome-app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: navidrome-pvc
  namespace: &ns media
  labels: &l
    app.kubernetes.io/name: &app navidrome
    pvc.home.arpa/volsync: "true"
    kustomization.flux.home.arpa/helmpatches: "false"
spec:
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  path: ./kube/deploy/core/storage/volsync/template
  dependsOn:
    - name: crds
      namespace: flux-system
  postBuild:
    substitute:
      PVC: &pvc "navidrome-data"
      SIZE: "5Gi"
      SC: &sc "block"
      SNAP: *sc
      ACCESSMODE: &am "ReadWriteOnce"
      SNAP_ACCESSMODE: *am
      VS_APP_CURRENT_VERSION: "ghcr.io/navidrome/navidrome:0.61.2@sha256:9fa40b3d8dec43ceb2213d1fa551da3dcfef6ac6d19c2e534efb92527c2bafd2"
      RUID: &uid "6969"
      RGID: *uid
      RFSG: *uid
      TRIGGER: "2026-05-03"
  healthChecks:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      name: *pvc
      namespace: *ns
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      name: "navidrome-data-r2-updates-restic"
      namespace: *ns
  healthCheckExprs:
    - apiVersion: volsync.backube/v1alpha1
      kind: ReplicationSource
      current: status.conditions.filter(s, s.status == "False").all(s, s.reason == "WaitingForManual" || s.reason == "WaitingForSchedule") && status.latestMoverStatus.result == "Successful"
      failed: status.latestMoverStatus.result == "Failed" # TODO: add failed conditions
  patches:
    - patch: |
        apiVersion: volsync.backube/v1alpha1
        kind: ReplicationDestination
        metadata:
          name: not-used
        spec:
          restic:
            restoreAsOf: "2026-05-03T14:00:00+00:00"
      target:
        group: volsync.backube
        kind: ReplicationDestination
        # labelSelector: pvc.home.arpa/rdst=navidrome-data-bootstrap
