---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
  namespace: *app
spec:
  interval: 5m
  chart:
    spec:
      chart: prometheus-smartctl-exporter
      version: 0.17.1
      sourceRef:
        name: prometheus-community
        kind: HelmRepository
        namespace: flux-system
  values:
    fullnameOverride: *app
    serviceMonitor:
      enabled: true
      attachMetadata:
        node: true
      relabelings:
        # replaces other node identifiers with hostname
        - action: replace
          regex: (.*)
          replacement: $1.${CLUSTER_NAME}
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
    prometheusRules:
      enabled: true
